// <auto-generated />
namespace TestApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class OrderDate_field_nullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderDate_field_nullable));
        
        string IMigrationMetadata.Id
        {
            get { return "202106030739028_OrderDate_field_nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
